# Generated by Django 4.1.1 on 2022-09-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="firstName",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="lastName",
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
