# Generated by Django 4.1.1 on 2022-09-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_profile_firstname_profile_lastname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="firstName",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="lastName",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
