# Generated by Django 4.1.1 on 2022-09-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_profile_firstname_alter_profile_lastname"),
    ]

    operations = [
        migrations.RenameField(model_name="profile", old_name="bio", new_name="story",),
        migrations.RenameField(
            model_name="profile", old_name="location", new_name="website",
        ),
    ]
