# Generated by Django 4.1.1 on 2022-09-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_bio_profile_story_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="id",),
        migrations.AlterField(
            model_name="profile",
            name="id_user",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
