# Generated by Django 4.1.1 on 2022-09-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_profile_id_alter_profile_id_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id_user",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
