# Generated by Django 4.1.1 on 2022-09-30 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_alter_profile_id_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="firstName",),
        migrations.RemoveField(model_name="profile", name="lastName",),
        migrations.RemoveField(model_name="profile", name="profile_img",),
        migrations.RemoveField(model_name="profile", name="story",),
        migrations.RemoveField(model_name="profile", name="website",),
        migrations.AlterField(
            model_name="profile",
            name="id_user",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
