# Generated by Django 4.1.1 on 2022-09-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_profile_firstname_remove_profile_lastname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="firstName",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="lastName",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(
                default="blank-profile-picture.png", upload_to="profile_images"
            ),
        ),
        migrations.AddField(
            model_name="profile", name="story", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="website",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id_user",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
