# Generated by Django 4.1.1 on 2022-09-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_profile_firstname_profile_lastname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="firstName",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="lastName",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
